version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: budgetbuddy-db
    restart: always
    environment:
      POSTGRES_DB: budgetbuddy
      POSTGRES_USER: budgetbuddy
      POSTGRES_PASSWORD: budgetbuddy
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
   pgdata: